---
- name: install Docker
  pacman:
    name: docker
  become: true

- name: install Docker-Compose
  pacman:
    name: docker-compose
  become: true

- name: enable Docker daemon
  systemd:
    name: docker.service
    state: started
    enabled: true
  become: true

- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

