---
- name: copy global gitconfig
  copy:
    src: git/.gitconfig
    dest: ~/

- name: copy work gitconfig
  copy:
    src: git/work/.gitconfig
    dest: ~/Projects/

- name: copy private gitconfig
  copy:
    src: git/private/.gitconfig
    dest: ~/MyProjects/

- name: copy global gitignore
  copy:
    src: git/ignore
    dest: ~/.config/git/

- name: install meld
  pacman:
    name: meld
  become: true

