---
- name: create ssh config directory
  file:
    path: "{{ path_ssh | dirname }}" 
    state: directory

- name: copy ssh config
  copy:
    src: ssh/config
    dest: "{{ path_ssh }}"
    mode: 0644

