---
- name: install neovim
  pacman:
    name: neovim
  become: true

- name: create vim autoload directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/

- name: copy vim config
  copy:
    src: vim/init.vim
    dest: ~/.config/nvim/

- name: install and update vim plugins
  command: /usr/bin/nvim -c ':PlugInstall' -c ':UpdateRemotePlugins' -c ':qall'

- name: set vim as default
  lineinfile:
    path: ~/.profile
    regexp: '^export EDITOR='
    line: export EDITOR=/usr/bin/neovim

